name: Default

on:
  pull_request:

env:
  CI: true

jobs:
  coveralls:
    name: Test with Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Install dependencies
        run: |
          go mod download -x
      - name: Run Unit tests
        run: |
          go test -covermode atomic -coverprofile=coverprofile ./...
